name: Data correction
description: Report an error or suggest a correction to existing CNV data.
labels: [data-correction]
body:
  - type: input
    id: cnv-name
    attributes:
      label: CNV name
      placeholder: e.g., 22q11.2 copy number variant
    validations:
      required: false

  - type: textarea
    id: correction-details
    attributes:
      label: Correction details
      description: Describe the data you want to correct, and explain what should be changed or fixed.
      placeholder: e.g., The gene listed for 22q11.2 deletion is incorrect. It should include TBX1...
    validations:
      required: true
