name: Build CNV YAML files

on:
  repository_dispatch:
    types: [cnv-data-updated]

jobs:
  build-yamls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout cnv-booklet
        uses: actions/checkout@v3

      - name: Clone cnv-data
        run: |
          git clone https://github.com/alexandra-valeanu/cnv-data.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas openpyxl pyyaml

      - name: Run YAML builder script
        run: python scripts/build_yaml_files.py

      - name: Commit and push updated YAMLs
        run: |
          git config --global user.name "alexandra-valeanu"
          git config --global user.email "valeanualexandra17@gmail.com"
          git add _cnvs/*.yml
          git diff --cached --quiet || git commit -m "Update CNV YAMLs from latest cnv-data"
          git push https://x-access-token:${{ secrets.CNV_RELEASE_AUTOMATION }}@github.com/alexandra-valeanu/cnv-booklet.git HEAD:main
